services:

  hub:
    build: ./hub
    container_name: hub
    volumes:
      - peers:/app/peers
      - ./authorized_users.txt:/app/authorized_users.txt:ro
      - ./wg_inactive_peers.txt:/app/wg_inactive_peers.txt
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820
      - 11434:11434
    environment:
      - HUB_PRIV_KEY=${HUB_PRIV_KEY}
      - DEFAULT_PEER_PUB_KEY=${DEFAULT_PEER_PUB_KEY}

  spoke:
    build: ./spoke
    deploy:
      replicas: 2
    pull_policy: always
    restart: always
    volumes:
      - configs:/app/wg-configs
      - ~/.cache/huggingface:/root/.cache/huggingface
      - models:/app/models
    healthcheck:
      test: ["CMD", "python3", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      # gives the container advanced control over networking, to ensure it can configure for the internal VPN
      - NET_ADMIN
    environment:
      - HUB_ENDPOINT=${HUB_ENDPOINT}
      - HUB_PUB_KEY=${HUB_PUB_KEY}
      - DEFAULT_PEER_PRIV_KEY=${DEFAULT_PEER_PRIV_KEY}
      - ENABLED_FOR_REQUESTS=${ENABLED_FOR_REQUESTS}
      - CHUNKER_WORKERS=1
      - CHUNKER_MAX_CONCURRENT_THREADS_PER_WORKER=4

volumes:
  peers:

  configs:
  models:
